#!/usr/bin/env python3
"""Derive your configuration from your netid; write src/config.h and the two
section 2.6 suspects, tests/suspects/suspect-1.c and suspect-2.c.

The derivation is sha256("<netid>:A5"), first 12 hex digits. It is written out
here so the starter is self-contained: the same derivation is applied to your
netid when your work is read, so do not edit this file - a changed rule gives
you a configuration, and suspects, nobody asked you to measure.

Which suspect is the broken one, and the line numbers inside both, depend on
your netid. `make` regenerates them whenever submission.json changes.
"""
import hashlib, json, sys
from pathlib import Path

LABEL = "A5"


def derive(netid: str, label: str = LABEL) -> int:
    h = hashlib.sha256(f"{netid.lower()}:{label.upper()}".encode()).hexdigest()
    return int(h[:12], 16)


def params(netid: str) -> dict:
    s = derive(netid)
    return {
        #: Ranges chosen so every configuration loses updates reliably: see
        #: tests/run-tests.sh check 4. A narrow window or too few iterations
        #: would let a genuinely racy program look correct, which is the one
        #: failure this assignment cannot afford.
        "threads": 4 + (s % 5),
        "iterations": 20000 + (s // 7 % 6) * 10000,
        "spin": 20 + (s // 13 % 40),
    }


# --- BEGIN SUSPECT GENERATOR ------------------------------------------------
# Do not edit: the same generator is run on your netid when your work is read,
# so suspects edited by hand, or made from another netid, are detected.
SUSPECT_REMARKS = [
    " * The configuration below is fixed; it is not your netid's.",
    " * Every thread spins SPIN iterations per count, as src/counter.c does.",
    " * The merge at the end of worker() is the only shared update.",
    " * Both suspects take the same A5_STRESS option and print the same way.",
]

SUSPECT_MERGE = {
    "one_section": (
        "    pthread_mutex_lock(&counter_lock);\n"
        "    long seen = counter;\n"
        "    spin(A5_STRESS);\n"
        "    counter = seen + mine;\n"
        "    pthread_mutex_unlock(&counter_lock);\n"),
    "split_section": (
        "    pthread_mutex_lock(&counter_lock);\n"
        "    long seen = counter;\n"
        "    pthread_mutex_unlock(&counter_lock);\n"
        "    spin(A5_STRESS);\n"
        "    pthread_mutex_lock(&counter_lock);\n"
        "    counter = seen + mine;\n"
        "    pthread_mutex_unlock(&counter_lock);\n"),
}


def split_suspect(s: int) -> int:
    return 1 + (s // 11) % 2


def suspect_source(s: int, n: int) -> str:
    kind = "split_section" if n == split_suspect(s) else "one_section"
    k = (s // (17 if n == 1 else 19)) % (len(SUSPECT_REMARKS) + 1)
    remarks = "".join(line + "\n" for line in SUSPECT_REMARKS[:k])
    return (
        f"/* COMP 310 - Week 5 - A5, handout section 2.6: suspect {n}.\n"
        " *\n"
        " * GENERATED from your netid by tests/config.py - do not edit; `make`\n"
        " * rewrites it whenever submission.json changes.\n"
        " *\n"
        " * A proposed faster fix for the lost update. Each thread counts into a\n"
        " * local, then adds its total to the shared counter once, at the end: 8\n"
        " * shared updates a run instead of 400,000. One of the two suspects is\n"
        " * correct and the other loses updates; which is which depends on your\n"
        " * netid.\n"
        + remarks +
        " *\n"
        f" *   make detect SUSPECT={n} STRESS=<width>        measures it for you\n"
        " *   cc -std=c11 -Wall -Wextra -O0 -pthread -DA5_STRESS=<width> \\\n"
        f" *      -o suspect tests/suspects/suspect-{n}.c    builds it by hand\n"
        " *\n"
        " * It prints \"<counter> <expected>\", like src/counter.c. A5_STRESS\n"
        " * lengthens the time between reading the shared counter and writing it\n"
        " * back; a normal build leaves it at 0.\n"
        " */\n"
        "#include <pthread.h>\n"
        "#include <stdio.h>\n"
        "#include <string.h>\n"
        "\n"
        "#define THREADS    8\n"
        "#define ITERATIONS 50000\n"
        "#define SPIN       40\n"
        "#ifndef A5_STRESS\n"
        "#define A5_STRESS  0\n"
        "#endif\n"
        "\n"
        "static long counter = 0;\n"
        "static pthread_mutex_t counter_lock = PTHREAD_MUTEX_INITIALIZER;\n"
        "\n"
        "static void spin(int n)\n"
        "{\n"
        "    for (volatile int i = 0; i < n; i++)\n"
        "        ;\n"
        "}\n"
        "\n"
        "static void *worker(void *arg)\n"
        "{\n"
        "    (void) arg;\n"
        "    long mine = 0;\n"
        "    for (long k = 0; k < ITERATIONS; k++) {\n"
        "        spin(SPIN);\n"
        "        mine = mine + 1;\n"
        "    }\n"
        + SUSPECT_MERGE[kind] +
        "    return NULL;\n"
        "}\n"
        "\n"
        "int main(void)\n"
        "{\n"
        "    pthread_t t[THREADS];\n"
        "\n"
        "    for (int i = 0; i < THREADS; i++) {\n"
        "        int rc = pthread_create(&t[i], NULL, worker, NULL);\n"
        "        if (rc != 0) {\n"
        "            fprintf(stderr, \"pthread_create: %s\\n\", strerror(rc));\n"
        "            return 1;\n"
        "        }\n"
        "    }\n"
        "    for (int i = 0; i < THREADS; i++) {\n"
        "        int rc = pthread_join(t[i], NULL);\n"
        "        if (rc != 0) {\n"
        "            fprintf(stderr, \"pthread_join: %s\\n\", strerror(rc));\n"
        "            return 1;\n"
        "        }\n"
        "    }\n"
        "    printf(\"%ld %ld\\n\", counter, (long) THREADS * ITERATIONS);\n"
        "    return 0;\n"
        "}\n")
# --- END SUSPECT GENERATOR --------------------------------------------------


def netid_from_submission(root: Path) -> str:
    try:
        j = json.loads((root / "submission.json").read_text())
    except Exception as e:
        print(f"cannot read submission.json: {e}", file=sys.stderr)
        sys.exit(2)
    n = (j.get("student") or "").strip()
    if not n or n == "yournetid":
        #: With the placeholder netid the starter still builds, so you can compile
        #: before editing submission.json. `tests/run-tests.sh` fails until your
        #: own netid is set, so no number is measured on the wrong configuration.
        print("warning: submission.json still says \"yournetid\" - using the "
              "placeholder configuration. Set your netid before you measure "
              "anything: every figure you report is checked against it.",
              file=sys.stderr)
        return "yournetid"
    return n


def write_if_changed(path: Path, text: str) -> None:
    #: Rewrite only on a change, so `make` rebuilds exactly when the netid's
    #: configuration changed and never because a check re-derived it.
    if not path.exists() or path.read_text() != text:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    netid = args[0] if args else netid_from_submission(root)
    p = params(netid)
    text = ("/* GENERATED by tests/config.py from your netid - do not edit. */\n"
            "#ifndef A5_CONFIG_H\n#define A5_CONFIG_H\n"
            f"#define A5_THREADS    {p['threads']}\n"
            f"#define A5_ITERATIONS {p['iterations']}\n"
            f"#define A5_SPIN       {p['spin']}\n"
            "#endif\n")
    write_if_changed(root / "src" / "config.h", text)
    for n in (1, 2):
        write_if_changed(root / "tests" / "suspects" / f"suspect-{n}.c",
                         suspect_source(derive(netid), n))
    print(f"netid:      {netid}")
    print(f"threads:    {p['threads']}")
    print(f"iterations: {p['iterations']}")
    print(f"spin:       {p['spin']}")
    print(f"expected total (threads x iterations): {p['threads'] * p['iterations']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
